// <auto-generated />
using Debit_Credit.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Debit_Credit.Migrations
{
    [DbContext(typeof(DebitDbContext))]
    partial class DebitDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Debit_Credit.Models.AmountTkClass", b =>
                {
                    b.Property<int>("amountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("amountTk")
                        .HasColumnName("NVARCHAR(50)")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("amountId");

                    b.ToTable("AmountTB");
                });

            modelBuilder.Entity("Debit_Credit.Models.CreditModelsClass", b =>
                {
                    b.Property<int>("CreditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreditDate")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("CreditTK")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("CreditTime")
                        .HasColumnType("NVARCHAR(100)");

                    b.HasKey("CreditID");

                    b.ToTable("CreditTB");
                });

            modelBuilder.Entity("Debit_Credit.Models.DebitModelsClass", b =>
                {
                    b.Property<int>("DebitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DebitDate")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("DebitTK")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("DebitTime")
                        .HasColumnType("NVARCHAR(100)");

                    b.HasKey("DebitID");

                    b.ToTable("DebitTB");
                });
#pragma warning restore 612, 618
        }
    }
}
